// Demo-only rule set. Selectors: 'id:<medId>', 'cls:<class>', 'tag:<tag>' or arrays of these.
// Rules are ordered from most specific to most generic; the engine keeps the first
// match per topic per drug pair, so specific messages win over generic ones.

const R = (a, b, sev, topic, title, msg, advice, alt) => ({ a, b, sev, topic, title, msg, advice, alt });

export const DRUG_DRUG = [
  R('cls:pde5', 'cls:nitrate', 'high', 'hypotension', 'Severe hypotension',
    'Both drugs widen blood vessels. Together they can cause a sudden, dangerous drop in blood pressure.',
    'Never combine. Avoid nitrates for 24 h after sildenafil or 48 h after tadalafil.',
    'Discuss non-PDE5 options for erectile dysfunction with the cardiologist.'),
  R('id:warfarin', ['id:clarithromycin', 'id:erythromycin', 'id:fluconazole', 'id:metronidazole', 'id:ciprofloxacin', 'id:levofloxacin', 'id:amiodarone', 'id:cotrimoxazole'],
    'high', 'inr', 'INR rise and bleeding',
    'This medicine slows warfarin breakdown, raising INR and the risk of serious bleeding.',
    'Check INR within 3-5 days and reduce the warfarin dose if needed.',
    'For infections, prefer an antibiotic with minimal warfarin effect (e.g. amoxicillin) where clinically suitable.'),
  R('id:warfarin', ['id:rifampicin', 'id:carbamazepine', 'id:phenytoin'], 'high', 'inr', 'Loss of anticoagulation',
    'Enzyme induction speeds up warfarin clearance, lowering INR and increasing clot and stroke risk.',
    'Monitor INR twice weekly; a large warfarin dose increase may be needed.'),
  R('id:simvastatin', 'tag:cyp3a4_strong', 'high', 'statin', 'Rhabdomyolysis risk',
    'Strong CYP3A4 inhibitors raise simvastatin levels many-fold, risking severe muscle breakdown and kidney injury.',
    'Pause simvastatin for the length of the course.',
    'Use azithromycin instead of clarithromycin, or switch to rosuvastatin.'),
  R('id:atorvastatin', 'tag:cyp3a4_strong', 'moderate', 'statin', 'Raised statin levels',
    'CYP3A4 inhibition increases atorvastatin exposure and the chance of muscle pain or damage.',
    'Limit atorvastatin to 20 mg or pause it during a short course; report muscle pain.',
    'Azithromycin, or switch statin to rosuvastatin.'),
  R(['id:simvastatin', 'id:atorvastatin'], ['id:diltiazem', 'id:verapamil', 'id:amiodarone'], 'moderate', 'statin', 'Raised statin levels',
    'This heart medicine reduces statin breakdown, increasing myopathy risk.',
    'Keep simvastatin at or below 20 mg/day; monitor for muscle pain.', 'Rosuvastatin is less affected.'),
  R('id:colchicine', 'tag:cyp3a4_strong', 'high', 'colchicine', 'Colchicine toxicity',
    'Colchicine levels can rise to toxic levels (diarrhoea, low blood counts, muscle damage).',
    'Avoid the combination or cut colchicine dose sharply.', 'Azithromycin instead of clarithromycin.'),
  R(['id:apixaban', 'id:rivaroxaban', 'id:ticagrelor', 'id:quetiapine', 'id:alprazolam', 'id:amlodipine', 'id:nifedipine', 'id:carbamazepine'], 'tag:cyp3a4_strong',
    'moderate', 'cyp', 'Raised drug levels',
    'Strong CYP3A4 inhibition increases the blood level of this medicine and its side-effects.',
    'Consider a dose reduction or choose an alternative anti-infective.'),
  R('tag:cyp3a4_sub', 'tag:inducer', 'high', 'inducer', 'Loss of effect',
    'Rifampicin, carbamazepine and phenytoin strongly speed up breakdown of this medicine, risking treatment failure.',
    'Avoid the combination, or monitor effect closely and increase the dose.'),
  R('id:clopidogrel', ['id:omeprazole', 'id:esomeprazole'], 'moderate', 'clopi', 'Reduced clopidogrel effect',
    'Omeprazole and esomeprazole block CYP2C19, which clopidogrel needs to work, raising stent clot risk.',
    'Switch the acid reducer.', 'Pantoprazole 40 mg is the preferred PPI with clopidogrel.'),
  R('id:digoxin', ['id:amiodarone', 'id:verapamil', 'id:clarithromycin'], 'high', 'digoxin', 'Digoxin toxicity',
    'Digoxin levels can double, causing nausea, visual changes and dangerous heart rhythms.',
    'Halve the digoxin dose and check a digoxin level.'),
  R('id:digoxin', ['cls:loop', 'cls:thiazide'], 'moderate', 'digoxin', 'Low potassium raises digoxin toxicity',
    'Diuretic-induced low potassium makes the heart more sensitive to digoxin.', 'Monitor potassium and keep it at or above 4.0 mmol/L.'),
  R('id:methotrexate', ['cls:nsaid', 'id:aspirin', 'id:cotrimoxazole'], 'high', 'mtx', 'Methotrexate toxicity',
    'Reduced methotrexate clearance can cause mouth ulcers and bone-marrow suppression.',
    'Avoid; if essential, monitor blood counts and kidney function.', 'Paracetamol for pain.'),
  R('id:lithium', ['cls:nsaid', 'cls:acei', 'cls:arb', 'cls:thiazide'], 'high', 'lithium', 'Lithium toxicity',
    'The kidneys clear less lithium, so levels rise (tremor, confusion, vomiting).',
    'Check lithium level within 5 days of starting.', 'Paracetamol for pain.'),
  R('id:theophylline', ['id:ciprofloxacin', 'id:erythromycin', 'id:clarithromycin'], 'high', 'theo', 'Theophylline toxicity',
    'Blocked metabolism raises theophylline levels, risking seizures and arrhythmia.',
    'Reduce theophylline dose and check levels.', 'Amoxicillin or azithromycin as the antibiotic.'),
  R(['cls:fluoroquinolone', 'cls:tetracycline'], ['cls:antacid', 'cls:calcium', 'cls:iron'], 'moderate', 'chelation', 'Reduced antibiotic absorption',
    'Calcium, iron, magnesium and aluminium bind the antibiotic in the gut so less is absorbed.',
    'Take the antibiotic 2 h before or 6 h after these products.'),
  R('id:levothyroxine', ['cls:calcium', 'cls:iron', 'cls:antacid', 'cls:ppi'], 'moderate', 'thyroid', 'Reduced levothyroxine absorption',
    'These products reduce how much thyroid hormone is absorbed, which can leave TSH high.',
    'Take levothyroxine on an empty stomach, at least 4 h apart from calcium, iron or antacids.'),
  R('cls:beta_blocker', 'cls:ccb_ndhp', 'high', 'brady', 'Heart block and bradycardia',
    'Both slow the heart; together they can cause very slow heart rate or heart block.',
    'Avoid the combination or monitor ECG and pulse closely.', 'Amlodipine is a safer calcium-channel blocker with beta-blockers.'),
  R(['cls:beta_blocker', 'id:amiodarone'], 'id:digoxin', 'moderate', 'brady', 'Additive slowing of heart rate',
    'Combined effect on the heart conduction system can cause bradycardia.', 'Monitor pulse; report dizziness or fainting.'),
  R('id:tramadol', ['cls:ssri', 'cls:snri', 'cls:tca'], 'high', 'serotonin', 'Serotonin syndrome and seizures',
    'Tramadol plus an antidepressant can cause serotonin syndrome (agitation, fever, tremor) and lowers the seizure threshold.',
    'Avoid this combination.', 'Paracetamol, with a topical NSAID if needed.'),
  R('id:valproate', 'id:carbamazepine', 'moderate', 'aed', 'Altered antiepileptic levels',
    'Each drug changes the level of the other, risking either toxicity or breakthrough seizures.', 'Check drug levels after starting.'),
  R('id:isoniazid', ['id:phenytoin', 'id:carbamazepine'], 'moderate', 'aed', 'Antiepileptic toxicity',
    'Isoniazid inhibits breakdown of the antiepileptic, raising its level.', 'Monitor drug levels and watch for unsteadiness.'),
  R('cls:sulfonylurea', ['id:fluconazole', 'id:clarithromycin', 'id:cotrimoxazole'], 'moderate', 'hypo', 'Low blood sugar',
    'This anti-infective raises sulfonylurea levels.', 'Check blood sugar more often during the course.'),
  R('tag:hypoglycemia', 'cls:beta_blocker', 'low', 'masked_hypo', 'Masked low-sugar warning signs',
    'Beta-blockers can hide shaking and palpitations that warn of low sugar.', 'Teach the patient to check sugar if sweaty or confused.'),
  R('id:aspirin', 'cls:p2y12', 'low', 'bleeding', 'Dual antiplatelet therapy',
    'Usually intentional after a stent or heart attack, but it does increase bleeding.',
    'Continue only for the prescribed duration and add gastro-protection (pantoprazole).'),
  R('id:ibuprofen', 'id:aspirin', 'moderate', 'cardio', 'Reduced aspirin heart protection',
    'Ibuprofen blocks low-dose aspirin from protecting platelets.', 'Take aspirin at least 30 min before ibuprofen, or avoid ibuprofen.', 'Paracetamol.'),
  R('id:rifampicin', ['id:isoniazid', 'id:pyrazinamide'], 'moderate', 'liver', 'Additive liver toxicity',
    'Standard TB combination, but liver injury risk adds up.', 'Check liver tests at baseline and monthly; stop if jaundice develops.'),

  // Generic class / tag rules
  R('cls:anticoagulant', 'cls:nsaid', 'high', 'bleeding', 'Major bleeding risk',
    'NSAIDs damage the stomach lining and affect platelets; with a blood thinner this can cause serious GI bleeding.',
    'Avoid NSAIDs while on anticoagulants.', 'Paracetamol for pain and fever.'),
  R('cls:anticoagulant', ['cls:antiplatelet', 'cls:p2y12'], 'high', 'bleeding', 'Major bleeding risk',
    'Two different blood-thinning mechanisms together greatly increase bleeding.',
    'Use only if a cardiologist specifically intends combined therapy; add a PPI.'),
  R('cls:anticoagulant', ['cls:ssri', 'cls:snri'], 'moderate', 'bleeding', 'Increased bleeding',
    'Antidepressants of this type reduce platelet serotonin, adding to anticoagulant bleeding risk.', 'Watch for bruising or black stools.'),
  R(['cls:antiplatelet', 'cls:p2y12'], 'cls:nsaid', 'moderate', 'bleeding', 'Stomach bleeding risk',
    'Combined effect on platelets and stomach lining raises GI bleeding risk.', 'Avoid regular NSAID use; add a PPI if unavoidable.', 'Paracetamol.'),
  R(['cls:ssri', 'cls:snri'], 'cls:nsaid', 'moderate', 'bleeding', 'Stomach bleeding risk',
    'SSRIs/SNRIs plus NSAIDs increase upper-GI bleeding risk several-fold.', 'Prefer paracetamol or add gastro-protection.', 'Paracetamol.'),
  R('tag:qt', 'tag:qt', 'high', 'qt', 'QT prolongation',
    'Both medicines lengthen the QT interval on ECG; together they raise the risk of a dangerous arrhythmia (torsades).',
    'Get a baseline ECG; avoid if QTc is above 470 ms; correct potassium and magnesium.'),
  R('tag:serotonergic', 'tag:serotonergic', 'high', 'serotonin', 'Serotonin syndrome',
    'Two serotonin-raising medicines can cause agitation, high fever, sweating and muscle twitching.',
    'Avoid or use the lowest doses with close monitoring.'),
  R('cls:opioid', ['cls:benzodiazepine', 'cls:hypnotic'], 'high', 'cns', 'Breathing suppression',
    'Opioids with sedatives can slow breathing dangerously, especially in older adults.', 'Avoid combination; if essential use lowest doses.'),
  R('tag:cns', 'tag:cns', 'moderate', 'cns', 'Excess sedation and falls',
    'Both cause drowsiness; combined they impair alertness and raise fall risk.', 'Avoid driving; use lowest effective doses.'),
  R(['cls:acei', 'cls:arb'], ['cls:acei', 'cls:arb', 'cls:k_sparing', 'cls:potassium'], 'high', 'k', 'High potassium',
    'Both raise potassium; dangerous hyperkalaemia can cause cardiac arrest, especially with kidney disease.',
    'Check potassium and creatinine within 1 week; avoid potassium supplements.'),
  R('tag:hyperkalemia', 'tag:hyperkalemia', 'high', 'k', 'High potassium',
    'Both medicines raise blood potassium.', 'Check potassium within 1 week.'),
  R('cls:nsaid', ['cls:acei', 'cls:arb'], 'moderate', 'kidney', 'Kidney strain and weaker BP control',
    'NSAIDs reduce kidney blood flow and blunt the effect of BP medicines.', 'Use the shortest NSAID course; check creatinine.', 'Paracetamol.'),
  R('cls:nsaid', ['cls:loop', 'cls:thiazide'], 'moderate', 'kidney', 'Reduced diuretic effect',
    'NSAIDs cause salt and water retention, reducing diuretic benefit and stressing the kidneys.', 'Avoid regular NSAID use.', 'Paracetamol.'),
  R('cls:nsaid', 'cls:corticosteroid', 'moderate', 'gi', 'Stomach ulcer and bleeding',
    'Steroids and NSAIDs together greatly increase ulcer risk.', 'Add a PPI (pantoprazole) if both are essential.'),
  R('tag:hypoglycemia', 'tag:hypoglycemia', 'moderate', 'hypo', 'Additive low blood sugar',
    'Two sugar-lowering drugs that can each cause hypoglycaemia.', 'Monitor glucose; reduce sulfonylurea dose if needed.'),
  R('tag:anticholinergic', 'tag:anticholinergic', 'moderate', 'achol', 'Anticholinergic burden',
    'Combined dry mouth, constipation, urine retention and confusion, especially in the elderly.', 'Reduce the number of anticholinergic medicines.'),
  R('tag:hepatotoxic', 'tag:hepatotoxic', 'moderate', 'liver', 'Additive liver toxicity',
    'Both medicines can stress the liver.', 'Check liver function tests periodically.'),
  R('tag:seizure', 'tag:seizure', 'moderate', 'seizure', 'Lower seizure threshold',
    'Both medicines can make seizures more likely.', 'Avoid in patients with epilepsy.'),
  R('cls:alpha_blocker', 'cls:pde5', 'moderate', 'hypotension', 'Dizziness on standing',
    'Additive blood-pressure lowering can cause fainting.', 'Start PDE5 inhibitor at lowest dose, 4 h apart from tamsulosin.'),
  R('cls:ppi', 'cls:ppi', 'moderate', 'dup', 'Two acid reducers', 'Two PPIs give no extra benefit.', 'Keep one PPI.'),
];

// Same-class pairs that are flagged as duplicate therapy unless listed here
export const ALLOWED_SAME_CLASS = new Set(['antitb', 'insulin', 'nitrate', 'antimalarial', 'antiepileptic']);

const F = (sel, food, sev, msg, advice) => ({ sel, food, sev, msg, advice });

export const DRUG_FOOD = [
  F('id:warfarin', 'Green leafy vegetables (spinach, methi, cabbage)', 'moderate',
    'Vitamin K in leafy greens counteracts warfarin; sudden changes swing the INR.', 'Keep leafy-green intake steady day to day rather than avoiding it.'),
  F('id:warfarin', 'Alcohol', 'high', 'Alcohol unpredictably changes INR and raises bleeding risk.', 'Avoid alcohol or limit to very small amounts.'),
  F('id:warfarin', 'Garlic, ginger, turmeric supplements', 'moderate', 'High-dose herbal supplements add to bleeding effect.', 'Normal cooking amounts are fine; avoid concentrated supplements.'),
  F('cls:anticoagulant', 'Cranberry & grapefruit juice', 'low', 'May slightly increase anticoagulant effect.', 'Avoid large amounts of these juices.'),
  F('id:simvastatin', 'Grapefruit juice', 'high', 'Grapefruit blocks simvastatin breakdown, raising levels and muscle damage risk.', 'Avoid grapefruit entirely.'),
  F(['id:atorvastatin', 'cls:ccb_dhp', 'id:alprazolam', 'id:quetiapine'], 'Grapefruit juice', 'moderate', 'Grapefruit raises blood levels of this medicine.', 'Avoid grapefruit and grapefruit juice.'),
  F('id:metronidazole', 'Alcohol', 'high', 'Causes a disulfiram-like reaction: flushing, vomiting, palpitations.', 'No alcohol during treatment and for 48 h after the last dose.'),
  F(['cls:benzodiazepine', 'cls:opioid', 'cls:antipsychotic', 'cls:tca', 'cls:hypnotic', 'id:chlorpheniramine'], 'Alcohol', 'high',
    'Alcohol multiplies sedation and can slow breathing.', 'Avoid alcohol completely.'),
  F('id:metformin', 'Alcohol', 'moderate', 'Heavy drinking with metformin raises the risk of lactic acidosis.', 'Limit alcohol; never drink on an empty stomach.'),
  F(['cls:sulfonylurea', 'cls:insulin'], 'Alcohol & skipped meals', 'moderate', 'Can cause sudden low blood sugar.', 'Eat regular meals; do not drink alcohol on an empty stomach.'),
  F(['cls:sulfonylurea', 'cls:insulin', 'id:metformin'], 'Bitter gourd (karela) juice', 'low', 'Additive sugar-lowering effect.', 'Monitor sugar if taking karela juice daily.'),
  F('id:paracetamol', 'Alcohol', 'moderate', 'Regular alcohol with paracetamol increases liver damage risk.', 'Avoid alcohol; do not exceed 3 g/day if you drink.'),
  F(['cls:nsaid', 'id:aspirin'], 'Alcohol', 'moderate', 'Increases risk of stomach bleeding.', 'Avoid alcohol while taking painkillers.'),
  F('cls:nsaid', 'Empty stomach', 'low', 'NSAIDs irritate the stomach lining.', 'Take after food or with milk.'),
  F(['cls:fluoroquinolone', 'cls:tetracycline'], 'Milk, curd, paneer & calcium-rich food', 'moderate', 'Calcium binds the antibiotic and reduces absorption.', 'Take the antibiotic 2 h before or 6 h after dairy.'),
  F('id:levothyroxine', 'Tea, coffee, soy & high-fibre breakfast', 'moderate', 'These reduce levothyroxine absorption.', 'Take with plain water 30-60 min before breakfast.'),
  F(['cls:acei', 'cls:arb', 'cls:k_sparing'], 'Potassium-rich food & salt substitutes (coconut water, bananas, Lona salt)', 'moderate',
    'Extra potassium can push blood potassium too high.', 'Avoid potassium salt substitutes; keep high-potassium foods moderate.'),
  F('cls:iron', 'Tea, coffee & milk', 'moderate', 'Tannins and calcium cut iron absorption by up to half.', 'Take iron 1 h before meals with vitamin C (amla, orange juice).'),
  F('id:lithium', 'Sudden changes in salt or caffeine', 'moderate', 'Low salt or dehydration raises lithium levels.', 'Keep salt and fluid intake steady; drink 2-3 L water daily.'),
  F('id:theophylline', 'Caffeine (tea, coffee, colas)', 'moderate', 'Caffeine adds to theophylline side-effects (palpitations, tremor).', 'Limit caffeine.'),
  F('id:isoniazid', 'Tyramine-rich food (aged cheese, fermented fish)', 'low', 'Can cause flushing, headache and palpitations.', 'Avoid aged cheese and fermented fish.'),
  F(['id:isoniazid', 'id:rifampicin', 'id:pyrazinamide', 'id:methotrexate', 'id:valproate'], 'Alcohol', 'high', 'Alcohol greatly adds to liver toxicity.', 'Avoid alcohol completely during treatment.'),
  F('id:rifampicin', 'Food at time of dose', 'low', 'Food reduces rifampicin absorption.', 'Take on an empty stomach, 1 h before breakfast.'),
  F('id:ciprofloxacin', 'Caffeine', 'low', 'Ciprofloxacin raises caffeine levels (jitteriness, insomnia).', 'Reduce tea and coffee.'),
  F('cls:pde5', 'Alcohol & heavy fatty meals', 'low', 'Alcohol adds to BP drop; fatty meals delay effect.', 'Avoid heavy alcohol.'),
  F(['cls:ssri', 'cls:snri'], 'Alcohol', 'moderate', 'Worsens drowsiness and depression.', 'Avoid alcohol.'),
  F(['id:digoxin', 'cls:loop', 'cls:thiazide'], 'Liquorice (mulethi)', 'moderate', 'Liquorice lowers potassium, adding to digoxin and diuretic risks.', 'Avoid mulethi products.'),
  F('cls:corticosteroid', 'High-salt & sugary food', 'low', 'Steroids raise blood sugar and cause fluid retention.', 'Reduce salt and sugar intake.'),
];

const D = (sel, diseases, sev, msg, advice, alt) => ({ sel, diseases, sev, msg, advice, alt });

export const DRUG_DISEASE = [
  D(['cls:nsaid', 'id:aspirin'], ['dengue'], 'high', 'NSAIDs and aspirin increase bleeding risk in dengue, where platelets are already falling.',
    'Stop NSAIDs/aspirin immediately.', 'Paracetamol only for dengue fever.'),
  D('cls:nsaid', ['ckd'], 'high', 'NSAIDs can worsen kidney function and cause acute kidney injury.', 'Avoid NSAIDs in kidney disease.', 'Paracetamol.'),
  D('cls:nsaid', ['heart_failure'], 'high', 'NSAIDs cause fluid retention and can trigger heart failure worsening.', 'Avoid NSAIDs.', 'Paracetamol.'),
  D(['cls:nsaid', 'id:aspirin'], ['peptic_ulcer'], 'high', 'High risk of ulcer bleeding.', 'Avoid; if unavoidable, add a PPI.', 'Paracetamol.'),
  D(['cls:nsaid', 'id:aspirin'], ['asthma'], 'moderate', 'Can trigger bronchospasm in aspirin-sensitive asthma.', 'Use with caution; stop if wheeze worsens.'),
  D('cls:nsaid', ['hypertension'], 'moderate', 'NSAIDs raise blood pressure and blunt BP medicines.', 'Use shortest course; monitor BP.'),
  D(['cls:anticoagulant', 'cls:antiplatelet', 'cls:p2y12'], ['bleeding_disorder', 'peptic_ulcer'], 'high', 'Active bleeding risk is greatly increased.', 'Specialist review before continuing.'),
  D('tag:nonselective_bb', ['asthma', 'copd'], 'high', 'Non-selective beta-blockers can cause severe bronchospasm.', 'Avoid.', 'Bisoprolol (cardio-selective) with caution, or a different BP class.'),
  D('cls:beta_blocker', ['bradycardia'], 'high', 'Further slows an already slow heart.', 'Avoid or reduce dose.'),
  D('cls:ccb_ndhp', ['heart_failure', 'bradycardia'], 'high', 'Verapamil/diltiazem weaken heart pumping and slow conduction.', 'Avoid.', 'Amlodipine if a CCB is needed.'),
  D('cls:corticosteroid', ['type2_diabetes', 'type1_diabetes'], 'moderate', 'Steroids raise blood sugar significantly.', 'Monitor glucose and adjust diabetes medicines.'),
  D('cls:corticosteroid', ['peptic_ulcer', 'osteoporosis'], 'moderate', 'Steroids worsen ulcers and bone loss.', 'Use the lowest dose; add PPI / calcium + vitamin D.'),
  D('cls:fluoroquinolone', ['myasthenia'], 'high', 'Fluoroquinolones can cause a dangerous myasthenic crisis.', 'Avoid.', 'Amoxicillin or cephalosporin, depending on infection.'),
  D(['cls:fluoroquinolone', 'id:tramadol', 'id:theophylline'], ['epilepsy'], 'high', 'Lowers seizure threshold.', 'Avoid in epilepsy.'),
  D('tag:qt', ['long_qt'], 'high', 'Can trigger a fatal arrhythmia in long QT syndrome.', 'Avoid all QT-prolonging medicines.'),
  D('tag:anticholinergic', ['glaucoma'], 'high', 'Can precipitate acute angle-closure glaucoma.', 'Avoid.', 'Non-anticholinergic alternatives (e.g. cetirizine, sertraline).'),
  D('tag:anticholinergic', ['bph', 'urinary_retention'], 'high', 'Can cause complete urinary retention.', 'Avoid.'),
  D(['tag:anticholinergic', 'cls:benzodiazepine'], ['dementia'], 'high', 'Worsens confusion and memory.', 'Avoid in dementia.'),
  D('tag:antipsychotic_risk', ['dementia'], 'high', 'Antipsychotics increase stroke and death risk in dementia.', 'Use only if severe and after specialist review.'),
  D('tag:dopamine_block', ['parkinsons'], 'high', 'Blocks dopamine and worsens Parkinson\u2019s symptoms.', 'Avoid.', 'Domperidone (for nausea) under monitoring.'),
  D(['cls:benzodiazepine', 'cls:opioid'], ['copd', 'sleep_apnea'], 'moderate', 'Can suppress breathing.', 'Use lowest dose or avoid.'),
  D(['cls:thiazide', 'cls:loop'], ['gout'], 'moderate', 'Diuretics raise uric acid and can trigger gout flares.', 'Monitor uric acid.', 'Losartan lowers uric acid slightly.'),
  D('id:metformin', ['liver_cirrhosis'], 'moderate', 'Higher lactic acidosis risk in liver failure.', 'Avoid in decompensated liver disease.'),
  D(['id:methotrexate', 'id:ketoconazole', 'id:valproate', 'id:isoniazid', 'id:rifampicin', 'id:pyrazinamide'], ['liver_cirrhosis', 'hepatitis_b', 'fatty_liver'], 'high',
    'Significant risk of further liver damage.', 'Specialist review and close liver monitoring.'),
  D(['cls:statin', 'id:paracetamol'], ['liver_cirrhosis'], 'moderate', 'Reduced liver capacity to clear this medicine.', 'Use reduced doses (paracetamol at or below 2 g/day).'),
  D(['cls:acei', 'cls:arb', 'cls:statin', 'id:warfarin', 'id:methotrexate', 'id:valproate', 'cls:tetracycline', 'id:phenytoin', 'id:carbamazepine', 'id:lithium'], ['pregnancy'], 'high',
    'Known risk of harm to the unborn baby.', 'Stop and switch to a pregnancy-safe alternative.',
    'BP: labetalol/nifedipine. Infection: amoxicillin/cephalosporin. Epilepsy: levetiracetam (specialist).'),
  D(['cls:fluoroquinolone', 'cls:nsaid', 'id:tramadol', 'id:sumatriptan'], ['pregnancy'], 'moderate',
    'Use in pregnancy only if benefit outweighs risk; NSAIDs are unsafe after 20 weeks.', 'Review with the obstetrician.', 'Paracetamol for pain or fever.'),
  D(['cls:tetracycline', 'cls:fluoroquinolone', 'id:amiodarone', 'id:lithium'], ['breastfeeding'], 'moderate', 'Passes into breast milk.', 'Choose a breastfeeding-compatible alternative.'),
  D(['cls:acei', 'cls:arb', 'cls:k_sparing', 'cls:potassium'], ['ckd'], 'moderate', 'Raises potassium and can reduce kidney function at first.', 'Check potassium and creatinine 1-2 weeks after starting.'),
  D(['cls:ssri', 'cls:snri', 'cls:tca'], ['bipolar'], 'moderate', 'Antidepressant alone can trigger mania.', 'Use only with a mood stabiliser.'),
  D(['id:primaquine', 'id:cotrimoxazole', 'id:nitrofurantoin', 'id:ciprofloxacin'], ['g6pd'], 'high', 'Can cause haemolysis (breakdown of red blood cells).', 'Avoid in G6PD deficiency.'),
  D('id:levothyroxine', ['cad'], 'low', 'Over-replacement can trigger angina.', 'Start low (12.5-25 mcg) and increase slowly.'),
  D('cls:sglt2', ['uti'], 'low', 'Can increase genital and urinary infections.', 'Maintain hydration and hygiene; review if recurrent UTI.'),
  D('id:metoclopramide', ['epilepsy'], 'moderate', 'May lower seizure threshold.', 'Use with caution.', 'Ondansetron or domperidone.'),
  D(['cls:sympathomimetic', 'id:salbutamol', 'id:theophylline'], ['hyperthyroidism', 'cad'], 'low', 'Can increase heart rate and palpitations.', 'Monitor heart rate.'),
];

// Reference ranges for the clinical report panel
export const LAB_RANGES = {
  egfr: { label: 'eGFR', unit: 'mL/min/1.73m\u00b2', low: 60 },
  creatinine: { label: 'Serum creatinine', unit: 'mg/dL', low: 0.6, high: 1.3 },
  potassium: { label: 'Potassium', unit: 'mmol/L', low: 3.5, high: 5.0 },
  sodium: { label: 'Sodium', unit: 'mmol/L', low: 135, high: 145 },
  alt: { label: 'ALT (SGPT)', unit: 'U/L', high: 40 },
  ast: { label: 'AST (SGOT)', unit: 'U/L', high: 40 },
  inr: { label: 'INR', unit: '', high: 3.0, note: 'Target 2-3 on warfarin' },
  platelets: { label: 'Platelets', unit: '\u00d710\u00b3/\u00b5L', low: 150, high: 450 },
  hb: { label: 'Haemoglobin', unit: 'g/dL', low: 12, high: 17 },
  glucose: { label: 'Fasting glucose', unit: 'mg/dL', low: 70, high: 110 },
  hba1c: { label: 'HbA1c', unit: '%', high: 6.5 },
  tsh: { label: 'TSH', unit: 'mIU/L', low: 0.4, high: 4.5 },
  uricAcid: { label: 'Uric acid', unit: 'mg/dL', high: 7.2 },
  qtc: { label: 'QTc (ECG)', unit: 'ms', high: 450 },
  heartRate: { label: 'Heart rate', unit: 'bpm', low: 60, high: 100 },
};

const L = (lab, op, value, sel, sev, msg, advice, alt) => ({ lab, op, value, sel, sev, msg, advice, alt });

// Ordered most severe first; the engine keeps one alert per medicine per lab value.
export const LAB_RULES = [
  L('egfr', '<', 30, 'id:metformin', 'high', 'Metformin is contraindicated when eGFR is below 30 (lactic acidosis risk).', 'Stop metformin.', 'Linagliptin or insulin for glucose control.'),
  L('egfr', '<', 30, ['cls:nsaid', 'id:nitrofurantoin', 'id:dabigatran', 'cls:k_sparing'], 'high', 'Contraindicated or unsafe at this level of kidney function.', 'Stop or choose an alternative.'),
  L('egfr', '<', 45, 'id:metformin', 'moderate', 'eGFR 30-45: metformin dose must be limited.', 'Maximum 1000 mg/day; recheck eGFR every 3 months.'),
  L('egfr', '<', 45, 'cls:nsaid', 'high', 'NSAIDs can push reduced kidneys into acute injury.', 'Avoid NSAIDs.', 'Paracetamol.'),
  L('egfr', '<', 60, 'tag:renal', 'moderate', 'This medicine is cleared by the kidneys and needs a reduced dose at this eGFR.', 'Adjust dose for kidney function.'),
  L('egfr', '<', 60, 'cls:nsaid', 'moderate', 'Reduced kidney function increases NSAID kidney toxicity.', 'Shortest course only; recheck creatinine.', 'Paracetamol.'),
  L('potassium', '>', 5.0, 'tag:hyperkalemia', 'high', 'Potassium is already high and this medicine raises it further.', 'Hold the medicine and repeat potassium urgently.'),
  L('potassium', '<', 3.5, 'id:digoxin', 'high', 'Low potassium greatly increases digoxin toxicity.', 'Correct potassium before continuing digoxin.'),
  L('potassium', '<', 3.5, 'tag:qt', 'moderate', 'Low potassium adds to QT-prolongation risk.', 'Correct potassium and recheck ECG.'),
  L('potassium', '<', 3.5, 'tag:hypokalemia', 'moderate', 'This medicine lowers potassium further.', 'Add potassium supplement or a K-sparing agent.'),
  L('alt', '>', 120, 'tag:hepatotoxic', 'high', 'ALT is more than 3x the upper limit; this medicine can worsen liver injury.', 'Stop or hold and repeat liver tests.'),
  L('alt', '>', 80, 'tag:hepatotoxic', 'moderate', 'ALT is raised; this medicine can stress the liver.', 'Repeat liver tests in 1-2 weeks.'),
  L('inr', '>', 3.0, 'id:warfarin', 'high', 'Over-anticoagulated: INR above target range.', 'Withhold the next warfarin dose and recheck INR.'),
  L('inr', '>', 3.0, ['cls:nsaid', 'cls:antiplatelet', 'cls:p2y12'], 'high', 'High INR plus this medicine sharply raises bleeding risk.', 'Avoid until INR is back in range.'),
  L('qtc', '>', 470, 'tag:qt', 'high', 'QTc is already prolonged; this medicine lengthens it further.', 'Avoid or switch to a non-QT drug.'),
  L('qtc', '>', 450, 'tag:qt', 'moderate', 'Borderline QTc; this medicine may prolong it.', 'Repeat ECG after starting.'),
  L('heartRate', '<', 55, 'tag:bradycardia', 'high', 'Heart rate is already slow; this medicine slows it further.', 'Reduce dose or hold; check ECG.'),
  L('platelets', '<', 100, 'tag:bleeding', 'high', 'Low platelets plus a blood-thinning effect raises bleeding risk.', 'Avoid until platelets recover.', 'Paracetamol for fever/pain.'),
  L('glucose', '<', 70, 'tag:hypoglycemia', 'high', 'Blood sugar is already low; this medicine lowers it further.', 'Reduce the dose and review diet timing.'),
  L('tsh', '>', 4.5, 'id:levothyroxine', 'low', 'TSH is high: thyroid dose may be too low or absorption is poor.', 'Check timing with food/calcium/iron before increasing dose.'),
  L('tsh', '>', 4.5, 'id:amiodarone', 'moderate', 'Amiodarone can cause hypothyroidism.', 'Check thyroid function every 6 months.'),
  L('sodium', '<', 130, 'tag:hyponatremia', 'moderate', 'Low sodium; this medicine can lower it further (confusion, falls).', 'Recheck sodium; consider alternative.'),
  L('uricAcid', '>', 7.2, ['cls:thiazide', 'cls:loop'], 'moderate', 'Uric acid is high; diuretics raise it further.', 'Monitor for gout.'),
  L('hb', '<', 10, ['cls:anticoagulant', 'cls:nsaid'], 'moderate', 'Low haemoglobin; any bleeding would be poorly tolerated.', 'Investigate cause of anaemia.'),
  L('hba1c', '>', 9, 'cls:corticosteroid', 'moderate', 'Diabetes is poorly controlled; steroids raise sugar further.', 'Intensify glucose monitoring.'),
];

// Beers criteria alternatives for patients aged 65+
export const BEERS_ALT = {
  benzodiazepine: 'Sleep hygiene, CBT for insomnia; avoid long-term benzodiazepines.',
  hypnotic: 'Sleep hygiene, CBT for insomnia.',
  tca: 'Sertraline or escitalopram for depression.',
  antihistamine_sedating: 'Cetirizine or fexofenadine.',
  sulfonylurea: 'Gliclazide or a DPP-4 inhibitor (lower hypoglycaemia risk).',
  nsaid: 'Paracetamol or topical diclofenac gel.',
  antiemetic: 'Ondansetron (short term).',
  glycoside: 'Keep digoxin dose at or below 0.125 mg/day.',
};

export const ALLERGY_OPTIONS = [
  { id: 'penicillin', label: 'Penicillin', high: ['cls:penicillin'], low: ['cls:cephalosporin'] },
  { id: 'cephalosporin', label: 'Cephalosporin', high: ['cls:cephalosporin'], low: ['cls:penicillin'] },
  { id: 'sulfa', label: 'Sulfa drugs', high: ['cls:sulfonamide'], low: ['cls:thiazide', 'id:furosemide'] },
  { id: 'nsaid', label: 'NSAIDs / Aspirin', high: ['cls:nsaid', 'id:aspirin'] },
  { id: 'macrolide', label: 'Macrolides', high: ['cls:macrolide'] },
  { id: 'fluoroquinolone', label: 'Fluoroquinolones', high: ['cls:fluoroquinolone'] },
  { id: 'opioid', label: 'Opioids', high: ['cls:opioid'] },
  { id: 'statin', label: 'Statins', high: ['cls:statin'] },
];
