import React from "react";
import { Link } from "react-router-dom";
import { useReports } from "../context/ReportContext.jsx";
import { useLang } from "../i18n/LanguageContext.jsx";

const copy = {
  en: { title: "Confirm before viewing", lead: "This report is a draft for a clinical conversation. It is not a verified care plan.", noDraft: "No report draft is ready yet.", build: "Build a report", principle: "AI does not make the final decision", principleText: "OCR and software rules only collect possible findings. Two independent AI review services and authenticated clinician sign-off are not connected in this prototype. The two reviewer entries are simulated and cannot release a patient-ready report.", checklist: "What was checked", documents: "Reviewed documents", catalog: "Catalog matches", rules: "Sample interaction findings", ai: "AI reviewer A + B", doctors: "Doctor reviewers", pending: "Not connected", simulation: "Simulated entries only", ack: "I understand that this draft has not been medically verified and I will not change medicines based on it alone.", view: "Show draft report", report: "Master report · unverified draft", print: "Print / Save as PDF", speak: "Listen to summary", medicines: "Medicine reconciliation", findings: "Potential interaction links", clinic: "Clinic and prescription source files", handoff: "Questions for a clinician", question: "Confirm medicine names, doses, diagnoses, lab values, interactions and any suggested changes using validated sources.", empty: "No link in the sample rules. This does not establish safety.", source: "Provenance", reviewed: "Entered reviewer notes", reminder: "Set reminders only after a clinician confirms the schedule.", privacy: "This report stays in this tab. Printing to PDF is handled by your browser; choose Save as PDF in the print dialog." },
  hi: { title: "देखने से पहले पुष्टि करें", lead: "यह डॉक्टर से बातचीत के लिए मसौदा है, सत्यापित उपचार योजना नहीं।", noDraft: "रिपोर्ट का मसौदा तैयार नहीं है।", build: "रिपोर्ट बनाएँ", principle: "AI अंतिम निर्णय नहीं लेता", principleText: "OCR और सॉफ्टवेयर नियम केवल संभावित निष्कर्ष दिखाते हैं। दो स्वतंत्र AI सेवाएँ और प्रमाणित डॉक्टर की स्वीकृति इस प्रोटोटाइप से नहीं जुड़ी हैं। दो समीक्षक प्रविष्टियाँ नकली हैं और रोगी के लिए रिपोर्ट जारी नहीं कर सकतीं।", checklist: "क्या जाँचा गया", documents: "जाँचे गए दस्तावेज़", catalog: "दवा सूची मिलान", rules: "नमूना इंटरैक्शन", ai: "AI समीक्षक A + B", doctors: "डॉक्टर समीक्षक", pending: "जुड़े नहीं हैं", simulation: "केवल नकली प्रविष्टियाँ", ack: "मैं समझता/समझती हूँ कि इस मसौदे की चिकित्सीय पुष्टि नहीं हुई है और मैं केवल इसके आधार पर दवाएँ नहीं बदलूँगा/बदलूँगी।", view: "मसौदा रिपोर्ट दिखाएँ", report: "मुख्य रिपोर्ट · अप्रमाणित मसौदा", print: "प्रिंट / PDF सहेजें", speak: "सारांश सुनें", medicines: "दवाओं का मिलान", findings: "संभावित इंटरैक्शन", clinic: "क्लिनिक और पर्चे", handoff: "डॉक्टर से पूछने के प्रश्न", question: "मान्य स्रोतों से दवा का नाम, मात्रा, रोग, लैब परिणाम, इंटरैक्शन और बदलाव की पुष्टि करें।", empty: "नमूना नियमों में लिंक नहीं मिला। इससे सुरक्षा सिद्ध नहीं होती।", source: "स्रोत", reviewed: "दर्ज समीक्षक नोट", reminder: "डॉक्टर द्वारा समय तय होने के बाद ही रिमाइंडर रखें।", privacy: "रिपोर्ट इसी टैब में रहती है। PDF के लिए ब्राउज़र में Save as PDF चुनें।" },
  ta: { title: "பார்க்கும் முன் உறுதிப்படுத்தவும்", lead: "இது மருத்துவருடன் பேசுவதற்கான வரைவு; உறுதிசெய்யப்பட்ட சிகிச்சைத் திட்டம் அல்ல.", noDraft: "அறிக்கை வரைவு இல்லை.", build: "அறிக்கை உருவாக்கு", principle: "AI இறுதி முடிவை எடுக்காது", principleText: "OCR மற்றும் விதிகள் சாத்தியமான கண்டறிதல்களை மட்டும் காட்டும். இரண்டு சுயாதீன AI சேவைகளும் அங்கீகரிக்கப்பட்ட மருத்துவர் ஒப்புதலும் இந்த மாதிரியில் இணைக்கப்படவில்லை. இரண்டு மதிப்பாய்வாளர் பதிவுகளும் மாதிரிகள்; நோயாளிக்கு அறிக்கையை வெளியிட முடியாது.", checklist: "சரிபார்க்கப்பட்டது", documents: "ஆவணங்கள்", catalog: "பட்டியல் பொருத்தங்கள்", rules: "மாதிரி தொடர்புகள்", ai: "AI மதிப்பாய்வாளர் A + B", doctors: "மருத்துவர் மதிப்பாய்வாளர்கள்", pending: "இணைக்கப்படவில்லை", simulation: "மாதிரி பதிவுகள் மட்டும்", ack: "இந்த வரைவு மருத்துவ ரீதியாக உறுதிசெய்யப்படவில்லை; இதை மட்டும் வைத்து மருந்தை மாற்ற மாட்டேன் என்பதை புரிந்துகொள்கிறேன்.", view: "வரைவு அறிக்கையைப் பார்", report: "முழு அறிக்கை · உறுதிசெய்யாத வரைவு", print: "அச்சிடு / PDF ஆக சேமி", speak: "சுருக்கம் கேள்", medicines: "மருந்து ஒப்பீடு", findings: "சாத்தியமான தொடர்புகள்", clinic: "மருத்துவ அறிக்கை மற்றும் சீட்டுகள்", handoff: "மருத்துவரிடம் கேட்க", question: "மருந்து பெயர், அளவு, நோய், ஆய்வக மதிப்பு, தொடர்பு மற்றும் மாற்றத்தை உறுதிசெய்யப்பட்ட ஆதாரத்தில் சரிபார்க்கவும்.", empty: "மாதிரி விதியில் தொடர்பு இல்லை. இது பாதுகாப்பை உறுதி செய்யாது.", source: "ஆதாரம்", reviewed: "பதிவிட்ட குறிப்புகள்", reminder: "மருத்துவர் அட்டவணையை உறுதி செய்த பின் நினைவூட்டலை அமைக்கவும்.", privacy: "அறிக்கை இந்தத் தாவலில் இருக்கும். PDF-க்கு உலாவியில் Save as PDF தேர்வு செய்யவும்." },
};

const verificationCopy = {
  en: { title: "Dr. verification in process · demo", detail: "Two fictional reviewer entries are recorded. No authenticated doctor has reviewed or approved this draft (0/2).", queue: "View review queue", printed: "Doctor verification: demo handoff only · 0/2 authenticated approvals. Patient release blocked." },
  hi: { title: "डॉक्टर सत्यापन की प्रक्रिया · नमूना", detail: "दो काल्पनिक समीक्षक प्रविष्टियाँ दर्ज हैं। किसी प्रमाणित डॉक्टर ने इस मसौदे को जाँचा या स्वीकृत नहीं किया (0/2)।", queue: "समीक्षा कतार देखें", printed: "डॉक्टर सत्यापन: केवल नमूना चरण · 2 में से 0 प्रमाणित स्वीकृतियाँ। रोगी के लिए जारी करना बंद है।" },
  ta: { title: "மருத்துவர் சரிபார்ப்பு · மாதிரி", detail: "இரண்டு கற்பனை மதிப்பாய்வாளர் பதிவுகள் உள்ளன. அங்கீகரிக்கப்பட்ட மருத்துவர் இந்த வரைவை ஆய்வு செய்யவோ ஒப்புதல் அளிக்கவோ இல்லை (0/2).", queue: "மதிப்பாய்வு வரிசையைக் காண்", printed: "மருத்துவர் சரிபார்ப்பு: மாதிரி ஒப்படைப்பு மட்டும் · 2 இல் 0 அங்கீகரிக்கப்பட்ட ஒப்புதல்கள். நோயாளிக்கான வெளியீடு தடை." },
};

export default function Confirmation() {
  const { lang, pick } = useLang();
  const c = copy[lang];
  const verification = verificationCopy[lang];
  const { draft, acknowledged, setAcknowledged } = useReports();
  const speak = () => {
    if (!("speechSynthesis" in window) || !draft) return;
    speechSynthesis.cancel();
    const text = `${c.report}. ${draft.medicines.length} ${c.medicines}. ${draft.findings.length} ${c.findings}. ${c.principleText}`;
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = { en: "en-IN", hi: "hi-IN", ta: "ta-IN" }[lang];
    utterance.rate = 0.9;
    speechSynthesis.speak(utterance);
  };
  if (!draft) return <section className="page-flow"><h1>{c.title}</h1><p>{c.noDraft}</p><Link className="btn" to="/report">{c.build}</Link></section>;
  const counts = { high: 0, moderate: 0, low: 0 };
  draft.findings.forEach((finding) => { if (finding.severity in counts) counts[finding.severity]++; });
  return <section className="page-flow confirmation-page">
    <div className="page-heading"><div><span className="eyebrow">RELEASE CHECKPOINT</span><h1>{c.title}</h1><p>{c.lead}</p></div><span className="badge badge-warn">PATIENT RELEASE BLOCKED</span></div>
    <div className="card confirmation-principle"><span className="principle-mark">!</span><div><h2>{c.principle}</h2><p>{c.principleText}</p></div></div>
    <div className="card verification-return"><div><span className="eyebrow">SIMULATED REVIEW QUEUE</span><h2>{verification.title}</h2><p>{verification.detail}</p></div><Link className="btn btn-outline btn-small" to="/verification">{verification.queue} →</Link></div>
    <div className="card"><h2>{c.checklist}</h2><div className="confirmation-grid"><div><strong>{draft.documents.length}</strong><span>{c.documents}</span></div><div><strong>{draft.medicines.filter((medicine) => medicine.drugId).length}/{draft.medicines.length}</strong><span>{c.catalog}</span></div><div><strong>{draft.findings.length}</strong><span>{c.rules}</span></div><div><strong>0/2</strong><span>{c.ai} · {c.pending}</span></div><div><strong>0/2</strong><span>{c.doctors} · {c.simulation}</span></div></div></div>
    <div className="card acknowledgement"><label className="check"><input type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} />{c.ack}</label><p className="muted small">{c.privacy}</p></div>
    {acknowledged && <article className="report-sheet" id="master-report"><div className="report-watermark">UNVERIFIED DRAFT</div><div className="report-sheet-head"><div><span className="eyebrow">MEDSAFE · REPORT {draft.id.slice(0, 8).toUpperCase()}</span><h2>{c.report}</h2><p>{new Date(draft.createdAt).toLocaleString({ en: "en-IN", hi: "hi-IN", ta: "ta-IN" }[lang])}</p></div><div className="report-actions"><button className="btn btn-outline" onClick={speak}>{c.speak}</button><button className="btn" onClick={() => window.print()}>{c.print}</button></div></div><div className="report-metrics"><span><strong>{draft.medicines.length}</strong>{c.medicines}</span><span><strong>{counts.high}</strong>High</span><span><strong>{counts.moderate}</strong>Moderate</span><span><strong>{counts.low}</strong>Low</span></div><section><h3>{c.clinic}</h3><ul className="clinical-list">{draft.documents.map((document, index) => <li key={index}><strong>{document.name}</strong><span>{document.kind} · {document.source === "sample" ? "Fictional sample" : document.confidence === null ? "Entered text" : `OCR ${document.confidence}%`}</span><p className="report-excerpt">{document.text}</p></li>)}</ul></section><section><h3>{c.medicines}</h3><ul className="clinical-list">{draft.medicines.map((medicine, index) => <li key={index}><strong>{medicine.name}</strong><span>{[medicine.dose, medicine.frequency].filter(Boolean).join(" · ") || "Dose and schedule need confirmation"}</span><small>{medicine.drugId ? `Sample catalog: ${medicine.drugId}` : "Unmatched name · excluded from checks"}</small></li>)}</ul>{draft.skipped.length > 0 && <p className="notice">Excluded: {draft.skipped.join(", ")}</p>}</section><section><h3>{c.findings}</h3><p className="muted small">{c.source}: {draft.coverage}</p>{draft.findings.length ? draft.findings.map((finding, index) => <div className="report-finding" key={index}><span className={`severity-dot ${finding.severity}`} /><div><strong>{finding.title}</strong><small>{finding.type} · {finding.severity.toUpperCase()}</small><p>{pick(finding.message)}</p></div></div>) : <p>{c.empty}</p>}</section><section><h3>{verification.title}</h3><p>{verification.printed}</p></section><section><h3>{c.reviewed}</h3>{draft.reviewers.map((reviewer, index) => <p key={index}><strong>{reviewer.name} · {reviewer.specialty || c.doctors}</strong> <span className="badge badge-warn">SIMULATED / NOT AUTHENTICATED</span><br />{reviewer.note}</p>)}</section><section className="report-handoff"><h3>{c.handoff}</h3><p>{c.question}</p><p>{c.reminder}</p><strong>{c.principleText}</strong></section></article>}
    {!acknowledged && <p className="muted">{c.view} ↓</p>}
  </section>;
}
